# Generated by Django 5.1.7 on 2025-04-05 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(default='Unnamed', max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('color', models.CharField(max_length=200, null=True)),
                ('coat', models.CharField(max_length=200, null=True)),
                ('eyes', models.CharField(max_length=100, null=True)),
                ('pigment', models.CharField(max_length=100, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='creation date')),
                ('age', models.IntegerField(default=0)),
                ('health_points', models.IntegerField(default=100)),
                ('energy_points', models.IntegerField(default=100)),
                ('hunger', models.IntegerField(default=100)),
                ('thirst', models.IntegerField(default=100)),
                ('bladder', models.IntegerField(default=100)),
                ('exercise', models.IntegerField(default=100)),
                ('exploration', models.IntegerField(default=100)),
                ('social_needs', models.IntegerField(default=100)),
                ('social_skills', models.IntegerField(default=0)),
                ('grooming', models.IntegerField(default=100)),
                ('chewing', models.IntegerField(default=100)),
                ('mood', models.IntegerField(default=100)),
            ],
        ),
    ]
