# Generated by Django 5.1.7 on 2025-04-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caninsim_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='activity',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='dog',
            name='intelligent',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='dog',
            name='prey_drive',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('XS', 'miniature'), ('S', 'small'), ('M', 'medium'), ('L', 'big'), ('XL', 'huge')], default='M', max_length=150),
        ),
    ]
