# Generated by Django 5.1.7 on 2025-04-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caninsim_app', '0003_dog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='eyes',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='pigment',
        ),
        migrations.AddField(
            model_name='dog',
            name='eye',
            field=models.CharField(choices=[('BR', 'brown'), ('AM', 'amber'), ('LA', 'light brown amber'), ('YL', 'yellow'), ('YG', 'yellow green'), ('GR', 'grey'), ('CP', 'copper'), ('BL', 'blue'), ('AW', 'almost white blue'), ('WL', 'wall/heterochromia'), ('SP', 'split')], default='BR', max_length=150),
        ),
        migrations.AddField(
            model_name='dog',
            name='nose',
            field=models.CharField(choices=[('BK', 'black'), ('BLL', ''), ('LG', 'light gray'), ('GR', 'gray'), ('AB', 'almost black'), ('PL', 'purplish'), ('BF', 'butterfly'), ('DL', 'dudley'), ('SN', 'snow'), ('PN', 'pink'), ('BP', 'bright pink'), ('BR', 'brown')], default='BK', max_length=150),
        ),
        migrations.AlterField(
            model_name='dog',
            name='coat',
            field=models.CharField(choices=[('HS', 'hairless single heterozygous'), ('HL', 'hairless LETHAL homozygous'), ('LN', 'long'), ('WR', 'wire'), ('SM', 'smooth'), ('CS', 'curly smooth'), ('CL', 'curly long'), ('WS', 'wire smooth'), ('WL', 'wire long'), ('WC', 'wire curly')], default='SM', max_length=150),
        ),
    ]
