# Generated by Django 5.1.7 on 2025-04-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caninsim_app', '0004_remove_dog_eyes_remove_dog_pigment_dog_eye_dog_nose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='nose',
            field=models.CharField(choices=[('BK', 'black'), ('LG', 'light gray'), ('GR', 'gray'), ('AB', 'almost black'), ('PL', 'purplish'), ('BF', 'butterfly'), ('DL', 'dudley'), ('SN', 'snow'), ('PN', 'pink'), ('BP', 'bright pink'), ('BR', 'brown')], default='BK', max_length=150),
        ),
    ]
