# Generated by Django 5.1.7 on 2025-04-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caninsim_app', '0005_alter_dog_nose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='activity',
            new_name='active',
        ),
    ]
