# Generated by Django 5.2 on 2025-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caninsim_app', '0006_rename_activity_dog_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='coat',
        ),
        migrations.AddField(
            model_name='dog',
            name='base_color',
            field=models.CharField(choices=[('black', 'Black'), ('gold', 'Gold'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray')], default='brown', max_length=50),
        ),
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='dog',
            name='marking',
            field=models.CharField(choices=[('none', 'None'), ('blaze', 'Blaze'), ('socks', 'Socks'), ('patches', 'Patches'), ('mask', 'Mask')], default='none', max_length=50),
        ),
    ]
